### ISSUE TITLE
Use NSLinguisticTagger to detect the language you're translating from? 

### ISSUE THREAD

**Issue by JamalK** [ayanonagon/Polyglot#11]

**Comment by ayanonagon** [comment]
Hi thanks for the issue! If you don’t set the `fromLanguage`, it won’t pass that parameter to the API, which will automatically detect the language for you. If you want to have something like “translated from Dutch” on your app, yeah, having Polyglot detect the language locally would be helpful, since Microsoft’s API unfortunately does not return the language that it detected and translated from. I might get to this sometime, but pull-requests are appreciated. :octocat:

**Comment by JamalK** [comment]
Cool! I will fork it, find a good way to implement it, and submit a pull request :+1:

**Comment by ayanonagon** [comment]
Great, thank you! Let me know if you have any questions. :smile_cat:
